{% set version = "1.4.304" %}

package:
  # There is already a conda-forge packaged named volk
  # We use the ubuntu name vulkan-volk to avoid conflict
  # https://launchpad.net/ubuntu/+source/vulkan-volk
  name: vulkan-volk
  version: {{ version }}

source:
  url: https://github.com/zeux/volk/archive/refs/tags/{{ version }}.tar.gz
  sha256: ab3d4a8ccaeb32652259cdd008399504a41792675b0421d90b67729ee274746f

build:
  number: 1
  # This is designed to be a header only / statically linked library
  # run_exports:
  #   - {{ pin_subpackage('vulkan-volk', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not unix]
    - make   # [unix]
  host:
    - libvulkan-headers
    - libvulkan-loader

test:
  commands:
    - test -f ${PREFIX}/include/volk.h  # [unix]
    - test -f ${PREFIX}/include/volk.c  # [unix]
    - test -f ${PREFIX}/lib/libvolk.a   # [unix]
    - if not exist %PREFIX%\\Library\\lib\\volk.lib exit 1  # [win]

about:
  home: https://github.com/zeux/volk
  summary: volk is a meta-loader for Vulkan.
  description: |

    It allows you to dynamically load entrypoints required to use Vulkan
    without linking to vulkan-1.dll or statically linking Vulkan loader.
    Additionally, volk simplifies the use of Vulkan extensions by automatically
    loading all associated entrypoints. Finally, volk enables loading Vulkan
    entrypoints directly from the driver which can increase performance by
    skipping loader dispatch overhead.

    volk is written in C89 and supports Windows, Linux, Android and macOS (via
    MoltenVK).

  license: MIT
  license_family: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hmaarrfk
    # eunos is interested in aarch64 and pcc64le
    - eunos-1128
